[package]
name = "aoc-control"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
crossterm = "0.27"
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
