[mgr]
ratio = [0, 1, 0]
show_hidden = true
sort_by = "natural"
sort_sensitive = false
show_symlink = true
linemode = "none"

[preview]
script = "~/.config/yazi/preview.sh"
max_width = 120
max_height = 40
