[mgr]
ratio = [0, 1, 0]
title_format = ""
show_hidden = true
sort_by = "natural"
sort_sensitive = false
show_symlink = true
linemode = "none"
mouse_events = ["click", "scroll"]

[preview]
script = "~/.config/yazi/preview.sh"
max_width = 120
max_height = 40
