[package]
name = "aoc-taskmaster"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
aoc-core = { path = "../aoc-core" }
anyhow = "1.0"
crossterm = "0.27"
notify = "6.1"
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fs2 = "0.4.3"
