[workspace]
members = [
    "aoc-installer",
    "aoc-cli",
    "aoc-core",
    "aoc-hub-rs",
    "aoc-agent-wrap-rs",
    "aoc-control",
    "aoc-mission-control",
    "aoc-taskmaster",
]
resolver = "2"
